version: '3.5'
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.6
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:5.4.1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_NO: 1
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_HOST_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xmx512m -Xms512m"

  kafka-manager:
    container_name: kafka-manager
    image: kafkamanager/kafka-manager
    links:
      - zookeeper:zookeeper
    ports:
      - 9000:9000
    depends_on:
      - zookeeper
    environment:
      - ZK_HOSTS=zookeeper:2181

  redis:
    container_name: redis
    image: redis:5
    ports:
      - 6379:6379