server:
  port: 7070

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      retries: 3
    consumer:
      group-id: order
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      enable-auto-commit: on
      auto-offset-reset: latest
    listener:
      type: single
      missing-topics-fatal: false
      poll-timeout: 3000ms
      concurrency: 1
